Tutorial 10 - HuggingFace
Adamage/tutorials pull request #101
Opened 2021-10-20 14:56 UTC by plutasnyy

2021-10-20 15:18 UTC, plutasnyy commented on tutorials/huggingface/README.md
> +More optimizers can be [here](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/reference.html#optimizers).
can be **found** here

2021-10-21 07:49 UTC, Adamage reviewed
Amazing tutorial, really happy this came together finally.

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +© Copyright 2020, The Hugging Face Team, Licenced under the Apache License,
since this is addition to graphcores repo, should we also mention graphcore here

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +### Environment preparation
this is level 3 "###" right after level 1 "#"  . Maybe one more heading of level 2 would be nice

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +because it is not accepted as input to the model.
could you link the nice table with all the settings combinations? that was HF tokenizer docs I think

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +
maybe there is a way to apply the `shuffle`, `rename_column`, and `set_format` before train/test split?

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +    torchscript=True
whats this setting?

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +    ipu_id = index // 4 + 1
well lets maybe just rename it right on top
```python
for ipu_id, layer in enumerate(...)
```

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +this task could be solved using inheritance.
do you mean inheritance from the Electra class in `transformers` package?

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +    def forward(self, input_ids, token_type_ids, attention_mask, labels):
I am wondering if we could just use kwargs here, would that still work with a lesser function signature. We obfuscate the code but then we gain conciseness

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +Compilation may take a few minutes. More information about the wrapping function
I would mention that a few minutes on 4 devices. The user might use 2 or 16 :)

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +automatically synchronise the updated weights of the model and transfer them
this is nice to know. Do you have any docs about this?

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +    trainingModel.attachToDevice()
why do we actually need to do this?

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +    val_epoch()
this looks short and really to the point

2021-10-21 07:49 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +in other tutorials you are encouraged to check out [Graphcore Tutorials](https://github.com/graphcore/tutorials).
we could link also the BERT inference example from the other repo
https://github.com/graphcore/examples/tree/master/applications/pytorch/bert

2021-10-21 13:33 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +    torchscript=True
I'm not entirely sure :P
> TorchScript is a way to create serializable and optimizable models from PyTorch code

https://pytorch.org/docs/stable/jit.html

2021-10-21 13:38 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +this task could be solved using inheritance.
yes

2021-10-21 13:44 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +automatically synchronise the updated weights of the model and transfer them
Honestly can't find this anywhere to add a link, maybe @dirkbrink knows where to find it?

2021-10-21 13:45 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +    trainingModel.attachToDevice()
I mentioned this before compilation, do you think it requires to be mentioned here too?
> In addition, the compilation of the model automatically attaches it to the device. We would like to use only one model (for the training or the inference) on the device at a time, as this will allow us to use a larger model. Therefore, we call `detachFromDevice` to detach the model from the IPU device.

2021-10-21 14:11 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +### Environment preparation
done

2021-10-21 14:11 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +because it is not accepted as input to the model.
done

2021-10-21 14:11 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +
done

2021-10-21 14:12 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +    ipu_id = index // 4 + 1
changed, please check if it is something you though: 
```python
ipu_ids = [1] * 4 + [2] * 4 + [3] * 4
for index, (layer, ipu_id) in enumerate(zip(model.electra.encoder.layer, ipu_ids)):
    model.electra.encoder.layer[index] = poptorch.BeginBlock(
        layer, f"Encoder{index}", ipu_id=ipu_id
    )
```

2021-10-21 14:13 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +    def forward(self, input_ids, token_type_ids, attention_mask, labels):
good point, I tried to change it, howevere poptorch arg_parser doesn't allow for things like that, or even passing dictionary as an argument :C

2021-10-21 14:13 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +Compilation may take a few minutes. More information about the wrapping function
done

2021-10-21 14:13 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +in other tutorials you are encouraged to check out [Graphcore Tutorials](https://github.com/graphcore/tutorials).
Good point, done

2021-10-21 14:50 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +© Copyright 2020 Graphcore Ltd. All rights reserved.
New line should be added here for proper formatting in jupyter notebook

2021-10-22 08:54 UTC, Adamage commented on tutorials/huggingface/walkthrough.py
> +    def forward(self, input_ids, token_type_ids, attention_mask, labels):
Well then. Maybe it's a good idea to write it out here explicitly as comment, that the `forward` function needs to have in signature all the arguments explicitly, the same arguments as the composed `self.model`

2021-10-25 15:14 UTC, dirkbrink requested changes
Review until line 159 in README...tbc

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/requirements.txt
> +transformers
Please have the requirements file point to specific versions of these packages

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/walkthrough_code_only.py
> +# © Copyright 2020 Graphcore Ltd. All rights reserved.
Our copyright should be the first. Also 2021 for the GC copyright.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/walkthrough.py
> +Version 2.0
Keep the Hugging Face copyright on one line

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +transformers library using IPUs. It is based on [Fine-tuning a pretrained model](https://huggingface.co/transformers/training.html).
...from the Hugging Face transformers library...

It is base on Hugging Face's [fine-tuning a pretrained model]

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +We use the IMDB dataset as our data. It contains movie reviews together with
We use the IMDB dataset for this tutorial.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +# Fine-tuning a pretrained transformer
Hugging Face: Fine-tuning a pretrained transformer

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +The text must be transformed into a form understandable by the model.
Before we can use the dataset, the text...

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +takes as input a batch from the dataset and returns a tokenized examples.
...and returns the tokenised representation.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +in the [preprocessing data](https://huggingface.co/transformers/preprocessing.html#everything-you-always-wanted-to-know-about-padding-and-truncation).
You can read more about data preprocessing in the Hugging Face transformers library [here].

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +the model.
because we do not need it as an input to our model.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +tutorial. The model description together with implementation details can be
into this tutorial.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +found in [HuggingFace documentation](https://huggingface.co/transformers/model_doc/electra.html).
can be found in the [Hugging Face transformers documentation].

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +When the data has been processed, we can adjust it to the input of our model.
we can adjust it to be an appropriate input format for our model.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +To do this, we rename the column and set the format to `torch`, which will make
which ensures the data is stored in the PyTorch tensor format.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +the `DataLoader` class from Pytorch we will use the implementation from
PyTorch

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +PopTorch, which inherits from Pytorch and is optimised for memory usage and
PyTorch
...and performance on the IPU.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +before getting the results back.
However, the user will have to wait for the IPU to complete all the iterations before anything is returned to the host machine.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +**Device iteration** is one cycle of loop, which runs entirely on the IPU
**Device iteration** specifies the number of batches that are executed on an IPU before interacting with the host. The higher the number...

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +**Anchor mode** specifies which data is returned from the model located on the
...is returned from the IPU to the host machine.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +performance, due to the overhead of transferring more data to the host machine.
This has an adverse impact on throughput due to the overhead of having to transfer more data to the host machine after N device iterations.

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +equally with 4 layers on each device on each of 3 devices, finally we place
...of the remaining 3 devices. Finally we place the ... on the last device as well (`IPU:3`)

2021-10-25 15:14 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +Let's define how to split the model between the IPU devices. We use 4
For this example we will pipeline the model across 4 IPU devices. We start by placing the embedding layer on the first device `IPU:0`.

2021-10-25 23:02 UTC, dirkbrink requested changes
Part 2

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +`poptorch.BeginBlock()`, which takes as arguments the instance of
In order to placer a given layer on a particular IPU device...
...which takes as arguments an instance of...
...the name of the layer (which is displayed in the [PopVision Graph Analyser])

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +We need to take one more step in order to adapt the model from HuggingFace to
...the model from the Hugging Face transformers library to run on an IPU.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +the returned loss in `identity_loss`. Here we use the composition, however,
I don't understand the first part of this last sentence?

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +Now, we create `trainingModel` and `inferenceModel`, for this task we use the
Now, we create a model for training and another for inference, using `poptorch.trainingModel` and `poptorch.inferenceModel` respectively.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +`poptorch.trainingModel` and `poptorch.inferenceModel`. They take an instance
They both take as arguments a `torch.nn.Module` instance and a `poptorch.Options` instance which we have previously instantiated. An optimiser is also required for `poptorch.trainingModel`.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +translation of our model to a program that can be run using IPU. Then we will
...that can be executed on an IPU.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +In addition, the compilation of the model automatically attaches it to the
Is that true about the device attachment? In that case, why do you use the explicit `attachToDevice` calls later?

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +device. We would like to use only one model (for the training or the inference)
We only need to execute one model at a time (between training and inference), therefore we call `detachFromDevice` to explicitly detach each model after compilation. This ensures we aren't holding IPUs unnecessarily and reducing overall utilisation.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +Compilation may take a few minutes when using 4 devices. More information about
...few minutes for this model.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +Our model and data are ready to run on IPU. We proceed to implement the
...on the IPUs.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +the model will have the current state and copying the weights between devices
...the weights explicitly between devices...

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +The function to validate is marked with the decorator `torch.no_grad()`,
The function that performs validation is marked with the decorator `torch.no_grad()`, which ensures that gradient calculations are skipped since they are not necessary.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +HuggingFace for sentiment prediction using IPU devices. If you are interested
...the Hugging Face transformers library..
...using IPUs.

2021-10-25 23:02 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +and for more advanced example can be found in [BERT example](https://github.com/graphcore/examples/tree/master/applications/pytorch/bert).
and for a more advanced BERT implementation, see this Graphcore [BERT example].

2021-10-26 08:39 UTC, plutasnyy commented on tutorials/huggingface/README.md
> +the returned loss in `identity_loss`. Here we use the composition, however,
I thought here about programming concepts [link](https://betterprogramming.pub/inheritance-vs-composition-2fa0cdd2f939). I think this sentence is not necessary

2021-10-26 09:00 UTC, plutasnyy commented on tutorials/huggingface/README.md
> +In addition, the compilation of the model automatically attaches it to the
I tested this and:
```python
inferenceModel.compile(**next(iter(eval_dataloader)))
print(inferenceModel.isCompiled())
print(inferenceModel.isAttachedToDevice())
```
yields
```
Graph compilation: 100%|█████████████████████████████████| 100/100 [01:25<00:00]
True
True
```

The model is compiled once, before the training both models are detached from the device. I attach the model (train or inference) for the time of each phase, if I do not do this the model will be attached automatically?

2021-10-26 09:08 UTC, plutasnyy commented on tutorials/huggingface/walkthrough.py
> +    def forward(self, input_ids, token_type_ids, attention_mask, labels):
This is not necessary `ElectraForSequenceClassification` has mroe arguments that we have not used

2021-10-26 09:14 UTC, plutasnyy commented on tutorials/huggingface/README.md
> +In addition, the compilation of the model automatically attaches it to the
I tested and it will be attached

2021-10-26 09:19 UTC, plutasnyy commented on tutorials/huggingface/README.md
> +In addition, the compilation of the model automatically attaches it to the
I will add comment about this too

2021-10-26 09:20 UTC, plutasnyy commented on tutorials/huggingface/README.md
> +In addition, the compilation of the model automatically attaches it to the
I added:
> Explicit attaching the model to the device is not necessary, because calling the model will make it attached automatically, however, at the of the method we detach it using `detachFromDevice`.

2021-10-26 14:35 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +the returned loss in `identity_loss`. Here we use the composition, however,
Ah I see now! Yeah it isn't directly relevant to the tutorial so taking it out was fine

2021-10-26 15:34 UTC, dirkbrink requested changes
When compiling the models I get the following warnings:

```
[11:20:11.126] [poptorch:cpp] [warning] Unused input
```

Can you resolve this please?

2021-10-26 15:34 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +device. We only need to execute one model at a time (between training and
...to the IPU device when using the default [connection type](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/reference.html?highlight=compile#poptorch.Options.connectionType).

2021-10-26 15:34 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +In addition, the compilation of the model automatically attaches it to the
Based on my comment below I think you can get rid of this sentence

2021-10-26 15:34 UTC, dirkbrink commented on tutorials/huggingface/README.md
> +we detach it using `detachFromDevice`. It is worth noting here, that detaching
Note that at the end of the following function we explicitly detach the model from the IPUs it was using. This automatically synchronises the updated weights of the model and transfers them to the CPU, ...

2021-10-27 13:03 UTC, dirkbrink approved these changes

2021-10-27 14:29 UTC, merged