Code only tag
Adamage/tutorials pull request #108
Opened 2021-10-26 15:30 UTC by plutasnyy

2021-10-26 15:33 UTC, Adamage reviewed
Looks good to meee

2021-10-26 15:33 UTC, Adamage commented on sst/src/exporter/factory.py
> -        configure_extract_outputs_preprocessor
its not needed?

2021-10-26 15:39 UTC, plutasnyy commented on sst/src/exporter/factory.py
> -        configure_extract_outputs_preprocessor
I removed all configurations that set `.enabled=True` flag, while we initialize the preprocessor using:
`exporter.register_preprocessor(preprocessor, enabled=True)` it is not necessary

2021-10-26 15:41 UTC, Adamage approved these changes

2021-10-27 12:56 UTC, dirkbrink requested changes

2021-10-27 12:56 UTC, dirkbrink commented on sst/README.md
> +#### Hiding cells
I noticed that the markdown cell (comment delimited) cell above the code cell with the tag will also be hidden from the code only output...worth mentioning that in the README.

2021-10-27 13:08 UTC, dirkbrink commented on sst/README.md
> +#### Hiding cells
Oh never mind I'm being dumb...it just applies to both comment cells and code cells - the difference being you don't need the "#" in the comment cell

2021-10-27 13:08 UTC, dirkbrink approved these changes

2021-10-27 13:28 UTC, merged