Add splitting cells
Adamage/tutorials pull request #4
Opened 2021-09-20 13:55 UTC by plutasnyy

Closes #2

2021-09-20 15:03 UTC, Adamage requested changes

2021-09-20 15:03 UTC, Adamage commented on tutorials/sst/format_converter.py
> +            if not line.startswith('"""'):
`"""` add this as a constant above class def or somewhere

2021-09-20 15:03 UTC, Adamage commented on tutorials/sst/format_converter.py
> +            if current_cell_type == CellProcessingStatus.CODE:
what about two consecutive markdowns or code cells?

2021-09-20 15:03 UTC, Adamage commented on tutorials/sst/format_converter.py
> +                cell_lines.append(line)
we need to deal somehow with lines that contain only white spaces. Maybe check if the line has any information like `if line.strip()`

2021-09-20 15:03 UTC, Adamage commented on tutorials/sst/format_converter.py
> +            new_cell = self.get_cell(cell_lines, current_cell_type)
name the parameters here pls

2021-09-20 15:03 UTC, Adamage commented on tutorials/sst/format_converter.py
> +        source = '\n'.join(cell_lines)
`os.linesep`

2021-09-21 08:13 UTC, Adamage commented
@plutasnyy  also I think right now FormatConverter , when you look at it and think about what it's doing, it's in practice a class with only static methods. In Python I recommend to remove the class and put all it's methods outside as functions. Then the module should remain as a file called `format_converter` this way we have a small library which does format converting with no need to write `FileConverter()` each time, there is no benefit

2021-09-21 11:19 UTC, plutasnyy commented on tutorials/sst/format_converter.py
> +            if current_cell_type == CellProcessingStatus.CODE:
For two markdown cells, the script will work because the second markdown cell starts with a new tag (I will add a unit test).
In case of 2 cells with code, it is not possible at this moment, we have to come up with syntax and handle it additionally.

2021-09-21 11:22 UTC, plutasnyy commented on tutorials/sst/format_converter.py
> +                cell_lines.append(line)
This is done in the code preprocessor, I believe the user expects everything between markdown bracets to be in the final docs, so it shouldn't be handled there, however, I remove the new lines the new lines at the beginning and end of the code. I will check how it behave with whitespaces there.

2021-09-21 11:31 UTC, Adamage commented on tutorials/sst/format_converter.py
> +            if current_cell_type == CellProcessingStatus.CODE:
Ok it's cool. Two code cells maybe do not make sense right now. We can add this later if users expect it.

2021-09-21 11:31 UTC, Adamage commented on tutorials/sst/format_converter.py
> +                cell_lines.append(line)
Ok that's good enough

2021-09-21 11:45 UTC, merged