Single Source Tool for tutorial management
Adamage/tutorials pull request #50
Opened 2021-09-28 09:12 UTC by plutasnyy

# Overview
The general functionality of this tool can be described as a conversion tool between source code format and interactive or rendered formats such as Jupyter Notebooks or Markdown documents.

This tool can be used to facilitate a single source system of maintaining both the source code and artifacts which are published based on this source code, while at the same time reducing the need to manually edit the outputs each time the source changes. Additionally in order to obtain the outputs, code has to be executed on target hardware, thus providing early testing for the published outputs.

# Usage
See the README file.

# Unit tests
Execute using `pytest`

2021-09-29 07:19 UTC, Adamage commented on tutorials/sst/README.md
> +tutorials:
Created issue for this #53

2021-09-29 07:19 UTC, Adamage commented on tutorials/sst/src/batch_execution.py
> +TutorialConfig = namedtuple("TutorialConfig", "name source")
Created issue for this #53

2021-09-29 07:21 UTC, Adamage commented on tutorials/sst/.coveragerc
> +[run]
Created issue #54

2021-09-29 07:21 UTC, Adamage commented on codecov.yml
> +fixes:
Created issue #54

2021-09-29 07:21 UTC, Adamage commented on .github/workflows/python-app.yml
> +name: Python application
Created issue #54

2021-09-29 07:38 UTC, plutasnyy commented on tutorials/sst/README.md
> +pip3 install -e .
This command installs the package, thus you can run from anywhere in the filesystem using `sst` instead of directly pointing the path to the sst.py file

2021-09-29 11:01 UTC, plutasnyy commented on .github/workflows/python-app.yml
> +name: Python application
Done

2021-09-29 11:01 UTC, plutasnyy commented on .gitignore
> +*.ipynb_checkpoints
Done

2021-09-29 11:01 UTC, plutasnyy commented on tutorials/sst/.coveragerc
> +[run]
Done

2021-09-29 11:01 UTC, plutasnyy commented on tutorials/sst/README.md
> +pip3 install -e .
I added information about that in README

2021-09-29 11:02 UTC, plutasnyy commented on tutorials/sst/README.md
> +pytest .
Done

2021-09-29 11:02 UTC, plutasnyy commented on tutorials/sst/README.md
> +cd sst
Done

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/README.md
> +sst --help
After checking, it seems to me that the problem was in the wrong imports (which were working because of my, incorrectly set `PYTHONPATH`). I fixed the imports and it seems to me that it should now work without any modification in `PYTHONPATH`

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/README.md
> +# remove_output
Done

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/README.md
> + --execute/--no-execute
Done

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/README.md
> +sst convert2all --source path_to_you_python_file --output-dir path_to_your_directory
Done

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/README.md
> +sst batch_convert \
Done

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/README.md
> +tutorials:
Done

2021-09-29 11:04 UTC, plutasnyy commented on tutorials/sst/src/batch_execution.py
> +TutorialConfig = namedtuple("TutorialConfig", "name source")
Done

2021-09-29 11:05 UTC, plutasnyy commented on codecov.yml
> +fixes:
Done

2021-09-30 08:55 UTC, dirkbrink requested changes

2021-09-30 08:55 UTC, dirkbrink commented on tutorials/sst/README.md
> +sst --help
Yeah looks good now

2021-09-30 08:55 UTC, dirkbrink reviewed
When converting to Jupyter format, it should be `no-execute` by default. It appears to be executing by default which I think is the incorrect behaviour.

Also, when convert `py_with_import.py` to a Jupyter notebook and try to execute the cell, the import fails:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-12e8e1e73a19> in <module>
----> 1 from tests.static.function_to_import import hello
      2 
      3 hello('John')

ModuleNotFoundError: No module named 'tests.static'
```

2021-09-30 09:39 UTC, Adamage commented
@dirkbrink 

> Also, when convert `py_with_import.py` to a Jupyter notebook and try to execute the cell, the import fails:
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-2-12e8e1e73a19> in <module>
> ----> 1 from tests.static.function_to_import import hello
>       2 
>       3 hello('John')
> 
> ModuleNotFoundError: No module named 'tests.static'
> ```

I just tried this 
`sst convert -s py_with_import.py -o py_with_import.ipynb --execute`
And it produced an output  notebook with print statement executed as output of cell. Also all unit tests pass with this source file. Please tell us how was this executed on your machine

2021-09-30 09:49 UTC, Adamage commented on sst/src/batch_execution.py
> +# Copyright (c) 2019 Graphcore Ltd. All rights reserved.
created issue #68

2021-09-30 09:50 UTC, Adamage commented on tutorials/sst/src/utils/path.py
> +    here, extension = splitext(Path(__file__).parent.parent.parent / 'tests')
created issue #68

2021-09-30 09:50 UTC, Adamage commented on tutorials/sst/src/utils/path.py
> +STATIC_FILES = Path(get_tests_dir() + os.sep + 'static')
created issue #68

2021-09-30 10:12 UTC, plutasnyy commented
Strange, in my case works too, tested on each level: `sst` `sst/testts` and `sst/tests/static/`

2021-09-30 11:43 UTC, Adamage commented on tutorials/sst/src/format_converter.py
> +def code_preprocessor(input_source: str) -> str:
fixed by #70

2021-09-30 11:43 UTC, Adamage commented on tutorials/sst/src/format_converter.py
> +def remove_from_cell_source(cell: NotebookNode, string_to_remove: str) -> NotebookNode:
fixed by #70

2021-09-30 11:43 UTC, Adamage commented on tutorials/sst/src/utils/path.py
> +    here, extension = splitext(Path(__file__).parent.parent.parent / 'tests')
fixed by #70

2021-09-30 11:43 UTC, Adamage commented on tutorials/sst/src/utils/path.py
> +STATIC_FILES = Path(get_tests_dir() + os.sep + 'static')
fixed by #70

2021-09-30 11:44 UTC, Adamage commented on sst/src/batch_execution.py
> +# Copyright (c) 2019 Graphcore Ltd. All rights reserved.
fixed by #70

2021-09-30 11:45 UTC, Adamage commented
@dirkbrink 
>When converting to Jupyter format, it should be no-execute by default. It appears to be executing by default which I think is the incorrect behaviour.

Changed behavior so that:
- `convert` has default setting of `no-execute`
- `convert2all` never executes Jupyter
- `batch-convert` executes if you want, but only for Markdown

2021-09-30 12:20 UTC, dirkbrink commented
> @dirkbrink
> 
> > Also, when convert `py_with_import.py` to a Jupyter notebook and try to execute the cell, the import fails:
> > ```
> > ModuleNotFoundError                       Traceback (most recent call last)
> > <ipython-input-2-12e8e1e73a19> in <module>
> > ----> 1 from tests.static.function_to_import import hello
> >       2 
> >       3 hello('John')
> > 
> > ModuleNotFoundError: No module named 'tests.static'
> > ```
> 
> I just tried this `sst convert -s py_with_import.py -o py_with_import.ipynb --execute` And it produced an output notebook with print statement executed as output of cell. Also all unit tests pass with this source file. Please tell us how was this executed on your machine

Yeah so I mean I'm trying to actually run the notebook cell that's been outputted. So just open the outputted notebook and try to run the cell - hopefully you'll see the same behaviour then

2021-09-30 12:49 UTC, LRVerkin commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
What will the files be named when using this option?

2021-09-30 12:52 UTC, Adamage commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
It will be as the source file name without extension + their own respective extension, ie:
````
path_to_your_python_file.md
path_to_your_python_file.ipynb
path_to_your_python_file_pure.py         # here its also a suffix to indicate it was cleared of all markdown cells
```

2021-09-30 13:09 UTC, LRVerkin commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
Can you mention that in the doc?
Instead of "pure", could the pure Python file use the suffix "code"? It would be much clearer.

2021-09-30 15:11 UTC, dirkbrink commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
Agree

2021-10-01 08:43 UTC, dirkbrink commented
> @dirkbrink
> 
> > When converting to Jupyter format, it should be no-execute by default. It appears to be executing by default which I think is the incorrect behaviour.
> 
> Changed behavior so that:
> 
> * `convert` has default setting of `no-execute`
> * `convert2all` never executes Jupyter
> * `batch-convert` executes if you want, but only for Markdown

Thanks, did a few manual tests and I think this is better now.

2021-10-01 08:50 UTC, plutasnyy commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
I renamed parameter and updated docs

2021-10-01 09:07 UTC, Adamage commented
@dirkbrink   Coming back to the issue with imports.

Let's consider this simple case:

Make a new folder with files like so:
```
lib/lib.py
test.py
```
Contents of `lib.py`
```python
def myfun():
    print('hello')
    return 2
```

Contents of `test.py`
```python
from lib.lib import myfun

a = myfun()
print(a)
```

Now execute conversion:
`sst convert2all -s test.py -o .`

Now let's check how it works.

`python test.py`
```bash
Hello
2
```

And jupyter:
![image](https://user-images.githubusercontent.com/11834161/135594864-6f7c1e01-90a3-4480-b2d6-09b9a3b394e4.png)


So I think you had problems because maybe your notebook was in a different place than the original script. Or the example you took relied on the internal structure of repo and `__init___.py` files.

2021-10-01 10:25 UTC, dirkbrink commented
Thanks for the explanation, I indeed had outputted the notebook in a different directory, so the relative import didn't work, my bad!

Something to consider though...out of interest, would you be able to change the path of imports in the jupyter notebook output as part of the SST conversion process? Don't do anything yet, just curious

2021-10-01 10:31 UTC, Adamage commented
> Something to consider though...out of interest, would you be able to change the path of imports in the jupyter notebook output as part of the SST conversion process? Don't do anything yet, just curious

So let's say we would alter the imports but just in the outputs right? For example to account for the fact, that the output folder could be somewhere else, than the source file.
Right. I think this would be doable. Perhaphs we could go through the code , and for the import statements in that cell, somehow parse the import like `dir1.dir2.dir3` into a file system path, alter the file system path in whatever way we want, then we would again change that to `dir1.dir2` or `dir4` and save back as import statement.

We have access to the code in each preprocessor and also even before we start `nbconvert` functions.

I think we could mark a code cell with `# update_imports` or something like that

2021-10-01 14:33 UTC, dirkbrink reviewed
No need for the Copyright notice in the markdown (as discussed will confirm soon about whether we need it in the jupyter notebook)

As discussed, output filename optional args for `convert2all`.

2021-10-01 14:33 UTC, dirkbrink commented on sst/src/exporter/code_exporter.py
> +def shebang():
Decided we don't need/want the shebangs in the raw code output so you can get rid of this

2021-10-01 14:35 UTC, dirkbrink commented
> > Something to consider though...out of interest, would you be able to change the path of imports in the jupyter notebook output as part of the SST conversion process? Don't do anything yet, just curious
> 
> So let's say we would alter the imports but just in the outputs right? For example to account for the fact, that the output folder could be somewhere else, than the source file. Right. I think this would be doable. Perhaphs we could go through the code , and for the import statements in that cell, somehow parse the import like `dir1.dir2.dir3` into a file system path, alter the file system path in whatever way we want, then we would again change that to `dir1.dir2` or `dir4` and save back as import statement.
> 
> We have access to the code in each preprocessor and also even before we start `nbconvert` functions.
> 
> I think we could mark a code cell with `# update_imports` or something like that

Not necessary as Louise and I agreed that we'll be outputting to the same directory as the source file. Thanks for taking the time to consider this though

2021-10-01 16:10 UTC, dirkbrink commented on sst/src/constants.py
> +CODE_SUFFIX = '_code'
Can we change this suffix (again, sorry!) to `_code_only` please?

2021-10-04 08:11 UTC, Adamage commented on sst/src/constants.py
> +CODE_SUFFIX = '_code'
Done in https://github.com/Adamage/tutorials/pull/81

2021-10-04 08:11 UTC, Adamage commented on sst/src/exporter/code_exporter.py
> +def shebang():
Done in https://github.com/Adamage/tutorials/pull/81

2021-10-04 13:12 UTC, dirkbrink commented
Just messing about with comments, they don't seem to be in any of the outputs when occurring before the first markdown cell? And none of the comments (including "hello") show up in the Jupyter notebook...is that by design? I feel like normal comments should probably still show up in a code block.

```
#!/usr/bin/env python3
# Comments don't work here
"""
Example first cell
"""

def hello(name):
    print(f'Hello {name}!') #hello

"""
Example second cell
"""
# comments work here
```

2021-10-04 13:20 UTC, dirkbrink commented on sst/README.md
> +The exception is the transformation to python code, in which case to avoid overwriting the source file the suffix `_code`
`_code_only`

2021-10-04 13:20 UTC, dirkbrink commented on sst/README.md
> +path_to_your_directory/source_file_name_code.py
`_code_only`

2021-10-04 13:20 UTC, dirkbrink commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
No docs for `--markdown-name` arg yet?

2021-10-04 13:40 UTC, Adamage commented on sst/README.md
> +The exception is the transformation to python code, in which case to avoid overwriting the source file the suffix `_code`
Will be fixed by https://github.com/Adamage/tutorials/pull/86

2021-10-04 13:40 UTC, Adamage commented on sst/README.md
> +path_to_your_directory/source_file_name_code.py
Will be fixed by https://github.com/Adamage/tutorials/pull/86

2021-10-04 13:41 UTC, Adamage commented on sst/README.md
> +sst convert2all --source path_to_your_python_file --output-dir path_to_your_directory
Will be fixed by https://github.com/Adamage/tutorials/pull/86

2021-10-04 14:53 UTC, Adamage commented
@dirkbrink   today we merged these changes:
https://github.com/Adamage/tutorials/pull/81
https://github.com/Adamage/tutorials/pull/83
https://github.com/Adamage/tutorials/pull/86
https://github.com/Adamage/tutorials/pull/88

All comments were addressed.

2021-10-04 15:02 UTC, dirkbrink commented
Thanks for all your prompt changes!

Sorry, another one...if I have a comment next to the copyright then that also gets stripped from the markdown output

e..g 

```
# Comment before copyright
# Copyright Graphcore
# Comment after copyright
"""
Example first cell
"""

def hello(name):
    print(f'Hello {name}!') #hello
```

2021-10-04 18:27 UTC, plutasnyy commented
In this case, the script behaves as described in the README:

>**Shebangs**
> 
>When a script contains lines, which start with `#!`, the whole line will be removed from all outputs.
>**Copyright notice**
> 
> All markdown cells with word `copyright` (case-insensitive) will be removed from Markdown output type, while in other 
> types it will remain.

I expected that copyright information can also be multi-line, so the whole cell is deleted and not just the line containing `copyright` word. For that task I created #89 issue

2021-10-05 08:12 UTC, dirkbrink commented
> I expected that copyright information can also be multi-line, so the whole cell is deleted and not just the line containing `copyright` word. For that task I created #89 issue

Ahhh right, yeah that's a good point! We do have some examples that have multi line copyrights, and that makes it difficult. We can stick with the current behaviour, rather than trying to cover for every case - I guess it's unlikely that we'll have another kind of comment before the imports anyway

2021-10-05 09:53 UTC, dirkbrink commented
> Ahhh right, yeah that's a good point! We do have some examples that have multi line copyrights, and that makes it difficult. We can stick with the current behaviour, rather than trying to cover for every case - I guess it's unlikely that we'll have another kind of comment before the imports anyway

Although https://github.com/Adamage/tutorials/pull/69#discussion_r722047018 shows an example of where this could be a problem

2021-10-05 14:17 UTC, dirkbrink approved these changes
Happy to say everything looks good, thanks! If I come across anything else we can just open another PR with a fix. Squash and merge time 😄

2021-10-05 14:35 UTC, merged