PyTorch Tutorial 1 - basics - Jupyter and Markdown
Adamage/tutorials pull request #73
Opened 2021-10-01 09:14 UTC by Adamage

Educational texts remained untouched, except they were given syntax style for our generator.

Added output removing in multiple places.

Since images are generated when creating markdown, the old ones have been removed from repo - no need for all the static images exists anymore.

2021-10-01 16:11 UTC, dirkbrink requested changes
Regenerate output so that we can have `walkthrough_code_only.py` instead of `walkthrough_pure.py`.

For this repo, lets default to having the markdown called `README.md` please (which we'll be able to do with the optional args added to the SST)

2021-10-04 07:21 UTC, Adamage commented
- [ ] regenerate this after all changes done to https://github.com/Adamage/tutorials/pull/50

2021-10-04 16:00 UTC, dirkbrink requested changes

2021-10-04 16:00 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +annotations, PopTorch will use [PopART]
This link gets split across multiple lines, so doesn't render properly in the README - have you run this file through a max characters per line pep8 rule?

2021-10-04 16:00 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +using the `torch.jit.# trace` API. That means it inherits
torch.jit.trace

2021-10-04 16:00 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +1. Load the Fashion-MNIST dataset using `torchvision.datasets` and `poptorch.
Same here, just adding a space where it shouldn't in the markdown output because of the newline

2021-10-04 16:00 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +We will use SGD (https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/reference.html#poptorch.optim.SGD)
Make this a proper Markdown link?

2021-10-04 16:00 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough_code_only.py
> +#Copyright (c) 2021 Graphcore Ltd. All rights reserved.
Can we add a space between the # and the start of the comment? Presume this is something to be fixed in the SST

2021-10-05 07:16 UTC, Adamage commented on tutorials/pytorch/tut1_basics/walkthrough_code_only.py
> +#Copyright (c) 2021 Graphcore Ltd. All rights reserved.
No actually I made this by mistake manually and didnt notice :) SST doesnt make mistakes !

2021-10-05 07:30 UTC, Adamage commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +annotations, PopTorch will use [PopART]
I think I did this myself. Maybe an automated tool is better.

2021-10-05 08:13 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +annotations, PopTorch will use [PopART]
I'm not sure if an automated tool will do any better, I suspect it's not that context aware...but worth a try I guess

2021-10-05 08:17 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough_code_only.py
> +#!/usr/bin/env python3
I guess this shebang will disappear too when you regenerate the output?

2021-10-05 08:48 UTC, Adamage commented on tutorials/pytorch/tut1_basics/walkthrough_code_only.py
> +#!/usr/bin/env python3
yes now it all updated

2021-10-05 09:38 UTC, Adamage commented
@dirkbrink comments done

2021-10-05 14:34 UTC, dirkbrink requested changes

2021-10-05 14:34 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +`torchivsion`. This dataset, from [Zalando](https://github.com/zalandoresearch/fashion-mnist),
Typo "torchvision"

2021-10-05 14:34 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +Since we have detached our model from it's training from it's training device,
"from it's training" is repeated

2021-10-05 14:34 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +of labels nand a list of predictions as the input, both in the same order.
"nand" should be "and"

2021-10-05 14:34 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +achieve the same behaviour in pure PyTorch, you'd wrap your model with `torch.
`torch.nn.DataParallel` split across 2 lines

2021-10-05 14:34 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +This option sets the seed for the PRNG on the IPU. This is equivalent to
Why have you changed this explanation of the `randomSeed` from before? I believe the behaviour hasn't changed?

2021-10-06 08:00 UTC, Adamage commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +This option sets the seed for the PRNG on the IPU. This is equivalent to
You have a keen eye. I think it's because this is a rare case when README.md and code source were different. I will preserve the.one from README.md.
Also I am proof reading this whole thing again to avoid simple typos

2021-10-06 08:27 UTC, Adamage commented
@dirkbrink  Gave it one full sweep and fixed some more typos and changed description of that one parameter.
What do you think?

2021-10-06 10:16 UTC, dirkbrink requested changes
Just noticed that the markdown filename gets used as the path for the outputs. I think we'd rather use the original single source file name.

So in this case it should be `walkthrough_outputs` instead of `README-outputs`. Also note the underscore instead of dash. Can you open another PR for the SST with this change and then regenerate the output for this diff please?

Couple of small changes, but otherwise looks good to me!

2021-10-06 10:16 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
>      labels += label
Can you add a `poptorch_model_inf.detachFromDevice()` line to the end of this cell please? Otherwise the notebook hangs on to the IPUs after inference has finished.

2021-10-06 10:16 UTC, dirkbrink commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +to parallelize the model over the given number of IPUs. Additional parallelism
Please use UK English and change back to "parallelise" - same for below.

2021-10-06 11:55 UTC, plutasnyy commented
From my side it looks fine ;)

2021-10-06 11:59 UTC, Adamage commented on tutorials/pytorch/tut1_basics/walkthrough.py
> +to parallelize the model over the given number of IPUs. Additional parallelism
For some reason I thought it's due to different meaning. Now it's clear, sure!

2021-10-06 12:27 UTC, dirkbrink approved these changes
LGTM

2021-10-06 12:42 UTC, merged