Pytorch Tutorial 5 - MNIST classification
Adamage/tutorials pull request #91
Opened 2021-10-05 10:39 UTC by Adamage

# Summary
I split all the functions used in the `__main__` because the main program and argument parsing have been removed.

Now the structure is linear and follows naturally from what has to be done - datasets loading, training, evaluating.

Added descriptions to steps and links to more documentation.

Changed a bit how TDQM is used.

2021-10-05 10:40 UTC, Adamage commented
Closing #66

2021-10-06 12:24 UTC, plutasnyy reviewed
Overall nice to read ;)

2021-10-06 12:24 UTC, plutasnyy commented on tutorials/pytorch/tut5_mnist/README.md
> +        else:
Ahhh 
> During the training, not every samples prediction is returned for efficiency reasons

Ok ;)

2021-10-06 12:29 UTC, Adamage commented
> I think you got the wrong folder, tutorial 5 is in `tutorials/simple_applications/pytorch/mnist/` ;)

Well yes but I moved it to `tutorials` ... I guess we would need to clarify where they should go.

2021-10-06 12:31 UTC, Adamage commented on tutorials/pytorch/tut5_mnist/README.md
> +```
It's a good point. Even more so because the transform is repeated. I will try it, although I have to check if I have to make a `deepcopy` or not.

2021-10-06 12:32 UTC, Adamage commented on tutorials/pytorch/tut5_mnist/README.md
> +        else:
Well yes I was wondering about it too until I found this mentioned in the comments of the original tutorial. However I don't like it. It's a bit unclear on why this happens, or if we can configure it or not etc..

2021-10-06 12:34 UTC, Adamage commented on tutorials/pytorch/tut5_mnist/README.md
> +`Block` which while define a simple 2D convolutional layer with pooling and
- [ ] fix wording line 105

2021-10-06 12:36 UTC, Adamage commented on tutorials/pytorch/tut5_mnist/README.md
> +        else:
- [ ] think about how to make this more understandable in the tutorial

2021-10-13 14:37 UTC, LRVerkin commented on simple_applications/pytorch/mnist/README.md
> +Let's define the elements of our neural network. First, we create the class
Readers are assumed to be ML engineers and knowledgeable about Pytorch, so we can keep Pytorch-specific explanations short: "Let's define the elements of our neural network. We first create a `Block` instance consisting of a 2D convolutional layer with pooling, followed by a ReLU activation".
We can drop links to Wikipedia too and assume that readers know about ML concepts.

2021-10-13 14:40 UTC, LRVerkin commented on simple_applications/pytorch/mnist/README.md
> +Now let's construct the deep neural network with 4 Convolutional layers and
It only has 2 convolution layers - layers 3 and 4 are linear layers (which is why in `forward`, the output of layer 2 needs to be flattened so it can be passed to the next Linear layer).
You can turn this into "Now, let's construct our neural network." without describing the content (it's a short network so the code is easy to read)

2021-10-13 14:40 UTC, arbfay requested changes

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +batches_per_step = 50
`device_iterations` instead of `batches_per_step`, for consistency with the other resources. It needs to be replaced in other places too.
```suggestion
device_iterations = 50
```

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +# The following is a workaround for pytorch issue #1938
I don't understand this comment. This issue pytorch/pytorch#1938 seems totally unrelated and is closed. I suppose the actual issue is pytorch/vision#1938 which is also closed.

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +urllib.request.install_opener(opener)
If the original issue has been solved in recent versions of `torchvision`, is this still necessary?

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +        self.softmax = nn.Softmax(1)
There's a `softmax` here, and then we use later a `CrossEntropyLoss`, which already uses a softmax (`LogSoftmax` more precisely). Can we either remove this `softmax`, or replace the `CrossEntropyLoss` with an `NLLLoss`?

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +of the PyTorch model. To perform the machine learning operations, we also
```suggestion
of the PyTorch model. To train the model, we also
```

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +of the PyTorch model. To perform the machine learning operations, we also
"machine learning operations" doesn't tell what we're doing next here

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +            with torch.inference_mode():
This is not needed as autograd is not enabled by this loop, and doesn't influence the PopTorch model
```suggestion

```

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +```
This is done implicitly now. We do not need it.
```suggestion

```

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +Subsequent calls will need to call `inference_model.copyWeightsToDevice()`.
PopTorch is not compiled on the first call, but the model is. Also, we do not need to call `inference_model.copyWeightsToDevice()`. This is really confusing here.
Instead, by reusing the [trained] model, the weights will be copied from the IPU back to the host, and they will be used to compile a new inference model.

2021-10-13 14:40 UTC, arbfay commented on simple_applications/pytorch/mnist/README.md
> +with torch.no_grad():
Again, no needed, there's no autograd involved.
```suggestion

```

2021-10-14 12:05 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +        self.softmax = nn.Softmax(1)
Let me check

2021-10-14 12:22 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +# The following is a workaround for pytorch issue #1938
Yes no longer needed

2021-10-14 12:24 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +Subsequent calls will need to call `inference_model.copyWeightsToDevice()`.
Changed the description please check

2021-10-14 12:24 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +Let's initiate the neural network from our defined classes.
Yes :)

2021-10-15 10:47 UTC, dirkbrink requested changes

2021-10-15 10:47 UTC, dirkbrink commented on simple_applications/pytorch/mnist/README.md
> +def accuracy(predictions, labels):
This doesn't seem to do anything useful during training...kind of sits at 100% and jumps to ~85 and back constantly. I would expect to see this slowly increasing during training.

2021-10-15 10:47 UTC, dirkbrink commented on simple_applications/pytorch/mnist/README.md
> +            preds, losses = training_model(data, labels)
Same with loss that just fluctuates around 0%...is this actually being calculated correctly?

2021-10-15 10:49 UTC, dirkbrink commented on simple_applications/pytorch/mnist/README.md
> +in `model.parameters()` will be copied from the IPU to the host. The trained
The weights from the trained model will be reused...

2021-10-18 10:50 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +def accuracy(predictions, labels):
Well yes but it seems the model learns really quickly. Considering this loop operates on `batch_size=8` and `device_iterations=50` each batch has 400 samples. But actually the values we have on the "surface" (as opposed to the IPU internal loop) are just the 8 samples. So if we have 7 predictions correct, we will get 87.5% accuracy, or 100% for 10, or 75% for 6, you see the pattern.
The same happens for the loss values, they still jump every now and then but quickly fall from >2 to close to 0 for majority.
![image](https://user-images.githubusercontent.com/11834161/137717259-ab6a1363-8942-4f67-ab5c-895de4a8ecc9.png)

@dirkbrink  Please let me know if this is enough for clarification, I could also keep the plots in the notebook if you think that it provides some educational value.

2021-10-18 17:07 UTC, Adamage commented
TODO to self:

- [ ] use AnchorMode to calculate accuracy and loss better (or allow a switch to enable this or not - `poptorch.AnchorMode.All` or `poptorch.AnchorMode.Sum`

2021-10-19 07:53 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +def accuracy(predictions, labels):
@dirkbrink  These are the same plots after setting `AnchorMode.All` . As suspected, the chaotic behavior was due to sampling just the last batch for accuracy and loss prompts for the user.
![image](https://user-images.githubusercontent.com/11834161/137867070-37c577ab-b6c4-416a-b9ff-2c5e395625bc.png)
I will add the Anchor mode explanation and incorporate it permanently into this tutorial.

2021-10-19 12:22 UTC, LRVerkin commented on simple_applications/pytorch/mnist/README.md
> +the cross-entropy loss function. To learn more about cross entropy click [here](https://en.wikipedia.org/wiki/Cross_entropy#Cross-entropy_loss_function_and_logistic_regression).
You can remove "To learn more about [...]" (same reasoning as above, intended audience are ML engineers who should know about this)

2021-10-19 12:28 UTC, LRVerkin commented on simple_applications/pytorch/mnist/README.md
> +performance as it is executing, values like accuracy or losses value will be
```suggestion
performance as it is executing, values like accuracy or losses will be
```

2021-10-19 12:36 UTC, dirkbrink requested changes
Nice addition with the anchor stuff

2021-10-19 12:36 UTC, dirkbrink commented on simple_applications/pytorch/mnist/README.md
> -        self.softmax = nn.Softmax(1)
Why did you remove the softmax?

2021-10-19 12:36 UTC, dirkbrink commented on simple_applications/pytorch/mnist/README.md
> +## How to use this demo
I feel like the 1,2,3 sections under this heading don't really make sense in the context of a notebook. Number 2 only matters when running the script itself. So please reword it. Also the hyperparameter setting in section 3 is fine, but the ordering doesn't make sense as it is now. Also, there is no new heading for the whole rest of the tutorial, so technically everything is under 3...probably needs a new heading to split up the rest of the notebook from the "How to use this demo" section

2021-10-19 13:29 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> -        self.softmax = nn.Softmax(1)
It was suggested by other reviewer. It's because cross entropy already includes this calculation. If I were to keep it, we could change cross entropy loss to NLL loss

2021-10-19 14:35 UTC, Adamage commented
@dirkbrink @LRVerkin  Thank you guys for the comments. I pushed changes addressing those requests, please check

2021-10-20 08:44 UTC, dirkbrink requested changes

2021-10-20 08:44 UTC, dirkbrink commented on simple_applications/pytorch/mnist/README.md
> +For further reading on hyperparameters, see [Hyperparameters (machine learning)](https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning))
Based on Louise's comments below, let's get rid of this sentence - our users will know what hyperparameters are

2021-10-20 09:56 UTC, Adamage commented on simple_applications/pytorch/mnist/README.md
> +For further reading on hyperparameters, see [Hyperparameters (machine learning)](https://en.wikipedia.org/wiki/Hyperparameter_(machine_learning))
Done in https://github.com/Adamage/tutorials/pull/91/commits/8d8fc4bafc5615c063da28c24f3721f08c12ac1e

2021-10-20 10:23 UTC, dirkbrink approved these changes
LGTM assuming Louise is also happy

2021-10-20 14:21 UTC, LRVerkin commented
LGTM as well

2021-10-21 07:10 UTC, merged