Tensorflow 2 Tutorial - Pipelining and Tensor Inspection
Adamage/tutorials pull request #93
Opened 2021-10-06 07:26 UTC by Adamage

Used previous README.md and documentation to add more educational text and visual help like graphics.

Had to refactor the code a bit and adjust formatting for our style rules.

The big code chunk underneath `strategy.scope()` was slimmed down so that it fits on one screen. Due to the fact that all graph compilation must happen under that context, it was all extracted to functions.

Closing #79

2021-10-08 09:08 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/mnist.py
> +Outfeed the activations for multiple layers in the second stage.
those two sentences sound weird

2021-10-08 09:11 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/mnist.py
> +    model = keras.Sequential([
explain difference between Keras `Sequential` and `Model`

2021-10-08 09:12 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/mnist.py
> +## Custom classes descriptions
this could be combined with the File Structure section?

2021-10-08 09:13 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/mnist.py
> +    outfeed_optimizer_mode = OutfeedOptimizerMode.AFTER_COMPUTE
explain what is `OutfeedOptimizerMode`

2021-10-08 09:14 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/mnist.py
> +):
this function uses `no_pipelining`, `use_gradient_accumulation` and `model_type` but they are not mentioned in the arguments

2021-10-11 15:30 UTC, dirkbrink requested changes
Part 1

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/requirements.txt
> +tensorflow==2.4.1
Take this out as it will grab the upstream tensorflow. If the user has already installed the Graphcore TF wheel then it will replace it, which we obviously don't want

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +# Tensorflow 2 tutorial for explaining pipelining and tensor
TensorFlow 2: Pipelining and Tensor Inspection Techniques

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Required imports.
Heading?

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +>The Tensorflow 2 distribution you need is bundled with Graphcore Poplar SDK!
The Graphcore TensorFlow 2 wheel is bundled with Graphcore Poplar SDK. Please ensure you install this wheel rather than the default public wheel. The Graphcore TensorFlow 2 wheel contains IPU specific functionality.

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Ensure proper Tensorflow version is installed.
Remove this line

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +if tf.__version__[0] != '2':
Remove this code block, I think the above is clear enough and this is semi pointless as it doesn't check for Graphcore vs default TF2 wheel

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +You will notice that a lot of code has been extracted to functions. This is
You will notice that a lot of code has been extracted to functions. This is mainly because when running in a Jupyter notebook most of the code has to be executed in the same Python context manager (which is scoped per cell). To avoid giant Jupyter notebook cells, you will only find invocations of functions later once the Tensorflow IPU context has been used.

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Create the helper function to use inside IPU context.
Please write in proper prose. These sentences sound more like bullet points. Worth explaining what the function is actually doing.

2021-10-11 15:30 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +More about [outfeed queues](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/perf_training.html#accessing-outfeed-queue-results-during-execution)
If you're interested you can read more about outfeed queues [here].

2021-10-13 17:22 UTC, HMellor reviewed
- All of my comments relatinv to steps per epoch/execution stem from the fact that originally this guide was for inspection (where epoch is more relevant), but now it is being repurposed to pipelining (where execution is more relevant)

- Some of the screenshots are dark mode, it might be more consistent with other documentation if all images were light mode

2021-10-13 17:22 UTC, HMellor commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## Selecting the pipelining feature
Configuring pipelinling?

2021-10-13 17:22 UTC, HMellor commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Initiate IPU configuration - more details here [`IPUConfig`](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/api.html#tensorflow.python.ipu.config.IPUConfig)
```suggestion
Initialise IPU configuration - more details here [`IPUConfig`](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/api.html#tensorflow.python.ipu.config.IPUConfig)
```

2021-10-13 17:22 UTC, HMellor commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## Selecting the Tensorflow IPU distribution strategy
Distribution strategy implies distributed computing

```suggestion
## Placing and training the model on IPU
```

2021-10-14 13:52 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/mnist.py
> +![Execution Trace](static/popvision_multiple_ipus.png)
Turns out I needed to zoom in the view a bit more

2021-10-15 08:55 UTC, hmellor reviewed
In my previous review I recommended changing steps per epoch to steps per execution because of the new pipelining focus.

If we still need to change the steps per epoch, then we should create a new variable `steps_per_epoch`. This way we can have lines that say `steps_per_execution=steps_per_execution` and `steps_per_epoch=steps_per_epoch`.

If you re-introduce the steps per epoch variable, then its presence should be explained. The explanation is as follows (this explanation also covers why decreasing gradient accumulation is helpful when attempting to inspect tensors):
>The gradient accumulation count determines the pipeline depth, so the number of activations and gradients added to the outfeed queues will be proportional to the gradient accumulation value. Additionally, the outfeed callback is called at the end of the epoch, so the number of steps per epoch will also affect the amount of data in the queues.

2021-10-15 08:55 UTC, HMellor commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +        steps_per_epoch=steps_per_execution,
This line should be removed if this is to be primarily a pipelining tutorial

2021-10-15 08:55 UTC, HMellor commented on feature_examples/tensorflow2/inspecting_tensors/mnist_code_only.py
> +        steps_per_epoch=steps_per_execution,
This line should be removed if this is to be primarily a pipelining tutorial

2021-10-18 07:14 UTC, Adamage commented
Closing PR. Will split this tutorial into two separate ones - tensor inspection and separately pipelining

2021-10-22 10:24 UTC, dirkbrink requested changes
Part 1

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +>**Note**
Maybe worth copying the "Setting up the environment" section from the other tutorials instead of having this note

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## File structure and local imports
This section should probably be above the required imports section as the first section in this tutorial

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
>  * `mnist.py` The main Python script.
Haven't included mnist_code_only in this list. Please use descriptions like in the other tutorials for the 4 files touched by the SST

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> -* `tests` Subdirectory containing test scripts.
Why did you get rid of this entry? Do the tests still run...that's important

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## General description for used model
General description of the model

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +By default, the example runs a three layer fully connected model, pipelined
the tutorial

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +If you change them for experimentation, re-run all the cells below including
...for experimentation in a Jupyter notebook, re-run all...

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Initialise IPU configuration - more details here [`IPUConfig`](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/api.html#tensorflow.python.ipu.config.IPUConfig)
more details [here]:

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## Placing and training the model on IPU
Training the model on an IPU

2021-10-22 10:24 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +More details here: [`IPUStrategy`](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/targeting_tf2.html#ipustrategy)
...inside of a strategy scope...

You can read more about the `IPUStrategy` scope [here].

2021-10-22 12:53 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +>**Note**
done

2021-10-22 12:53 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## File structure and local imports
done

2021-10-22 12:53 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
>  * `mnist.py` The main Python script.
done - also notebook was missing

2021-10-22 12:54 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> -* `tests` Subdirectory containing test scripts.
Well here it get's complicated. I pushed now a change to the tests, since we removed argument parsing from all the tutorials for the sake of Notebooks compatibility, the purpose of testing various user inputs is now gone. I changed it to just run the script. Let me know how that suits you.

2021-10-22 12:54 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## General description for used model
done

2021-10-22 12:54 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +By default, the example runs a three layer fully connected model, pipelined
done

2021-10-22 12:54 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +If you change them for experimentation, re-run all the cells below including
done

2021-10-22 12:54 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Initialise IPU configuration - more details here [`IPUConfig`](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/api.html#tensorflow.python.ipu.config.IPUConfig)
done

2021-10-22 12:55 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## Placing and training the model on IPU
done

2021-10-22 12:55 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +More details here: [`IPUStrategy`](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/targeting_tf2.html#ipustrategy)
done

2021-10-27 09:48 UTC, Adamage commented
@dirkbrink  Tests are now back. This PR used the new feature from this PR  https://github.com/Adamage/tutorials/pull/108 (*) and successfully this code passes all 6 tests, and also SST can generate content from it, skipping the argument parsing completely.

Some tests will still be removed as they were related to pipelining, and not tensor inspection.

(*) The final version that worked will be pushed there soon.

2021-10-27 14:43 UTC, dirkbrink requested changes

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +the host. Too learn more about using feeds, see [outfeed queues](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/api.html#outfeed-queue).
...from the IPU to the host. To learn more about using outfeeds, see [outfeed queues].

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +a small number of steps per execution to reduce memory footprint.
[steps per execution]

Add a link to the docs explaining what this is

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +printed to the standard output. In [`outfeed_callback.py`](./outfeed_callback.py)
Full url please...fyi we now have a master branch on tutorials that tracks latest SDK

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +This tutorial uses the following classes, which are implemented in libraries:
...which are implemented in [separate Python files]:

Add a link to the root of this example containing these other files

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +The gradient accumulation count `gradient_accumulation_steps_per_replica`
...accumulation count (`gradient_accumulation_steps_per_replica`) determines the ...

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +If you change them for experimentation in a Jupyter notebook, re-run all t
"the" is split across two lines

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Automatically set these parameters based on user input and configure the IPU
If the above `outfeed_pre_accumulated_gradients` variable is set to `True`, then modify the outfeed optimiser mode. You can read more about this in [outfeed_optimizer]:

Please use a full URL again please instead of relative

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +More details about the `IPUStrategy` [here](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/targeting_tf2.html#ipustrategy).
...about the `IPUStrategy` API can be found [here].

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +using the `tf.device` context.
...context that is used in TensorFlow1.

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Example callback outfeed print would look a bit like this:
When running the above cell in a notebook, you'll see something similar to this:

2021-10-27 14:43 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +## Profiling and Visualising for pipelining
I think you can get rid of everything from here onwards. Nice idea, but to be honest it's not the best example to show off. As you can see in the images you added, there is a huge external sync phase on IPU0 because we're never filling the pipeline, so it means utilisation of resources is poor. Probably not something we want to be showing off in a tutorial.

2021-10-28 07:39 UTC, Adamage commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Example callback outfeed print would look a bit like this:
Well in console it is also printed, hence I did not mention where exactly this can be found.

2021-10-28 16:10 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Example callback outfeed print would look a bit like this:
Sure, makes sense 👍

2021-10-28 16:17 UTC, dirkbrink requested changes

2021-10-28 16:17 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +Too learn more about using outfeeds, see [outfeed queues](https://docs.graphcore.ai/projects/tensorflow-user-guide/en/latest/api.html#outfeed-queue).
"To" not "Too"

2021-10-28 16:17 UTC, dirkbrink commented on feature_examples/tensorflow2/inspecting_tensors/README.md
> +a small number of [steps per execution[(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training.py#L537)
Link is broken...square bracket the wrong way round

2021-10-29 12:40 UTC, dirkbrink approved these changes
LGTM

2021-10-29 13:29 UTC, merged