Tutorial-2
Adamage/tutorials pull request #94
Opened 2021-10-06 10:30 UTC by plutasnyy

2021-10-06 10:34 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Real data throughput: 36088 items/s
I wonder if the result I got is correct. It is faster than the dataloader on CPU, and previously it was around ~40k items/s not ~130k

2021-10-06 10:53 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/walkthrough_code_only.py
> +if __name__ == '__main__':
I deleted code_only version and mentioned tuto_data_loading in README

2021-10-06 11:52 UTC, Adamage requested changes

2021-10-06 11:52 UTC, Adamage commented on tutorials/pytorch/tut2_efficient_data_loading/walkthrough.py
> +        pass
whats going on here?

2021-10-06 11:52 UTC, Adamage commented on tutorials/pytorch/tut2_efficient_data_loading/walkthrough.py
> +print('\nGlobal batch size 64 with synthetic data:')
since this message is static and we will be using Jupyter/MD, it could be just a markdown cell

2021-10-06 13:58 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/walkthrough.py
> +data_batch, labels_batch = next(iter(training_data))
I put this information above this code

2021-10-06 15:03 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/walkthrough.py
> +print('\nGlobal batch size 64 with synthetic data:')
You are right, done

2021-10-07 11:44 UTC, Adamage approved these changes

2021-10-11 09:54 UTC, dirkbrink requested changes
Is the reason why we don't have the `_code_only` output because of the asynchronous data accessor stuff? Maybe we can add in the `main` guards as comments, with a comment explaining to uncomment? Would that be messy do you think?

Or alternatively we leave the include guards in? Then as one step of the notebook we can guide the customer to comment out the guards for the purpose of the notebook. This way, if the customer tried to run the python file without reading any of the documentation it would still work.

2021-10-11 09:54 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +0) As we will often measure time we will prepare a class to help us work with it:
Start number from 1, doesn't seem to apply correctly in markdown

2021-10-11 09:54 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Note, that we manually terminated DataLoader object in order to inform the
This is only required in Jupyter notebooks, correct? If so maybe worth being more explicit. Also, note should be in a similar style to the note earlier about asynchronous data accessor

2021-10-11 09:54 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> -In that case, if the DataLoader throughput fell below 22170, it could be limiting.
Worth adding this comment back in about the dataloader not being a limiting factor (take out the absolute number though since it will vary a bit between runs)

2021-10-11 09:54 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +    DataLoader: 104683.40 items/s
These numbers don't make sense? 🤔

2021-10-11 09:54 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +--synthetic-data  # Run with IPU-generated synthetic data
Is this why we don't have a single source code_only output? If we do add the code only output, should we keep this file?

2021-10-12 09:20 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +0) As we will often measure time we will prepare a class to help us work with it:
done

2021-10-12 11:18 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +--synthetic-data  # Run with IPU-generated synthetic data
Check https://github.com/Adamage/tutorials/pull/94#issuecomment-940825224

2021-10-12 11:19 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Note, that we manually terminated DataLoader object in order to inform the
I took the description from tut 3

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
>     - The PopTorch Python library installed
```suggestion
   - The PopTorch Python library installed (see [Installation](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/installation.html) of the PopTorch User Guide)
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Let’s load the same model as in [the introductory tutorial on PopTorch](../tut1_basics)
You say reload, but it isn't imported from anywhere. 
```suggestion
Let’s reuse the model from [the introductory tutorial on PopTorch](../tut1_basics) 
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +any of these values then you should re-run all the cells below:
References to cells in the README are jarring

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +>**Note**: executing the code in python script requires an conditional block:
```suggestion
>**Note**: executing the code in python script requires the conditional block:
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +`self.fc1 = nn.Linear(972, 100)` to `self.fc1 = nn.Linear(41772, 100)`
When was it 972?

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +>it is necessary to avoid [issues with asynchronous DataLoader](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/batching.html#poptorch-asynchronousdataaccessor)
```suggestion
>This is necessary to avoid [issues with asynchronous DataLoader](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/batching.html#poptorch-asynchronousdataaccessor)
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Let’s set up a PopTorch DataLoader with asynchronous mode.
```suggestion
Let’s set up a PopTorch DataLoader in asynchronous mode.
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +The asynchronous mode of `poptorch.DataLoader` launches the data loading process
```suggestion
The asynchronous mode of `poptorch.DataLoader` performs the data loading
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +on a separate process to allow for the data to be preprocessed asynchronously
```suggestion
on a separate process. This allows the data to be preprocessed asynchronously 
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +option when the conditions described in the note above are met.
Is this sentence necessary?

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +batching. Mini-batches, replica batches, global batches... This section will
I don't think using elipsis matches the tone of the tutorial.

```suggestion
batching. Mini-batches, replica batches, global batches, etc. This section will 
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +the number of samples the DataLoader is going to fetch at one step.
```suggestion
the number of samples the DataLoader is going to fetch for one step.
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +gain can be obtained from it. If the model requires ***N*** IPUs and the
```suggestion
gain in throughput can be obtained from it. If the model requires ***N*** IPUs and the 
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
>  How to make sure the DataLoader is not a bottleneck for our model throughput?
```suggestion
How can we make sure the DataLoader is not a bottleneck for our model throughput?
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +>***Note for release of resources***:
```suggestion
>***Note about releasing resources***:
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +>might not happen due to training ending first before all samples are exhausted.
```suggestion
>might not happen due to training ending before all samples are exhausted.
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +
Why are these separate code blocks?

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
>  - Adjust the number of workers.
Specify how to adjust

```suggestion
- Increase the number of workers.
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +iteration will not.
```suggestion
iterations will not.
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +your DataLoader can consume all the dataset in the smallest number of steps
```suggestion
your DataLoader can consume the whole dataset in the smallest number of steps 
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
>  *Note: Compilation can take few minutes.*
Should this be in a note block?

```suggestion
>*Note: Compilation can take few minutes.*
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
>  - Asynchronous mode can provide better performance.
```suggestion
- Asynchronous mode can provide better throughput performance.
```

2021-10-14 13:49 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +- At one step, ***N = Global batch size x Device iterations*** samples will be
```suggestion
- During one step, ***N = Global batch size x Device iterations*** samples will be 
```

2021-10-15 08:19 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +
In order to hide output from the compilation of the model

2021-10-15 10:20 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
>     - The PopTorch Python library installed
Not resolved

2021-10-15 10:20 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Let’s load the same model as in [the introductory tutorial on PopTorch](../tut1_basics)
Not resolved

2021-10-15 10:20 UTC, HMellor commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +>**Note**: executing the code in python script requires an conditional block:
Not resolved

2021-10-20 14:09 UTC, dirkbrink requested changes
I added the following code below the imports:

```
from sys import exit 

"""
**The following cell is only necessary to prevent errors when running the source file as a script. If you're reading this in a Jupyter notebook, there is no need to run the next cell:**
"""
if __name__ == "__main__":
    print("This tutorial has been designed to run in a Jupyter notebook. If you would like to run it as a Python script, please use tuto_data_loading.py instead. This is required due to Python process spawning issues when using asynchronous data loading, as detailed in the README.")
    exit(0)
```

Please move the note explaining this to be next to this addition. It prevents errors when running the Python script on its own and isn't too obtrusive in my opinion.

2021-10-20 14:09 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +   - A Poplar SDK environment enabled (see [Installation](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/installation.html) of the PopTorch User Guide)
The comment from Harry should have been applied to the next bullet point. This bullet point was correct before

2021-10-20 14:09 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Let’s set up a PopTorch DataLoader in asynchronous mode.
The apostrophe in "Let's" is a different character, so when I run `convert` I get the following output: "Letâs" Please double check the rest of this file for these characters and replace

2021-10-21 11:23 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +`self.fc1 = nn.Linear(972, 100)` to `self.fc1 = nn.Linear(41772, 100)`
Done

2021-10-21 11:43 UTC, plutasnyy commented
In addition to 
```python
from sys import exit 

"""
**The following cell is only necessary to prevent errors when running the source file as a script. If you're reading this in a Jupyter notebook, there is no need to run the next cell:**
"""
if __name__ == "__main__":
    print("This tutorial has been designed to run in a Jupyter notebook. If you would like to run it as a Python script, please use tuto_data_loading.py instead. This is required due to Python process spawning issues when using asynchronous data loading, as detailed in the README.")
    exit(0)
```
I had to add validation if the script was run from a python file, not in jupyter, because I got an error while using `sst` ;P I took the simplest function from: https://stackoverflow.com/a/22424821
I tested this function using python script, jupyter notebook (just by using sst :smile:), and also in google colab

2021-10-21 11:44 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +Let’s set up a PopTorch DataLoader in asynchronous mode.
fixed, I will check that also in tutorials 7/10

2021-10-21 11:44 UTC, plutasnyy commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +   - A Poplar SDK environment enabled (see [Installation](https://docs.graphcore.ai/projects/poptorch-user-guide/en/latest/installation.html) of the PopTorch User Guide)
whoops, done

2021-10-22 08:18 UTC, dirkbrink requested changes

2021-10-22 08:18 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +>*Note: Compilation can take few minutes.*
This note about compilation time should either be removed completely or moved up to where compilation actually happens

2021-10-22 08:18 UTC, dirkbrink commented on tutorials/pytorch/tut2_efficient_data_loading/README.md
> +**The following cell is only necessary to prevent errors when running the
Sorry styling looks weird on this, think you can remove the bold text. With your change to the code it doesn't throw an error in the notebook so there's less need to bring attention to it - it's fine if someone runs the cell

2021-10-22 10:25 UTC, dirkbrink approved these changes
LGTM

2021-10-22 12:14 UTC, plutasnyy commented
What do you think @HMellor?

2021-10-22 14:05 UTC, hmellor approved these changes
LGTM

2021-10-22 14:08 UTC, merged