Tutorial 7
Adamage/tutorials pull request #98
Opened 2021-10-07 14:19 UTC by plutasnyy

Branches:
- `tutorial-7` - branch on which I added the version of tutorial-7 from .zip file that I received
- `tutorial-7-sst` - branch on which I transformed it into single source

2021-10-08 08:49 UTC, Adamage reviewed
Cosmetic propositions

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +for this reason, sharding is not recommended for production models where
IMHO this should be in **bold**. We should highlight what exactly is "good utilisation of IPU resource"

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +Note:
cosmetics - this could be a markdown note `>Note:...`

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +`effective batch size` = `mini-batch size` * `gradient accumulation count`
cosmetics - there are two ways to show this:

`effective batch size` = `mini-batch size` * `gradient accumulation count` 
or
`effective batch size = mini-batch size * gradient accumulation count` 

In the first the operators are misaligned, so people with OCD might get triggered :) :) :)

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +Performing gradient accumulation is valid because summing the gradients across
how about:

Performing gradient accumulation is **still** valid

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +to rerun all cells below
missing dot at end of sentence - I did find a few of those

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +    def generator():
IMHO this only wraps a single line and could be inlined. Up to your taste

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +    # Use 'drop_remainder=True' because XLA (and the compiled static IPU graph)
Quite a big chunk of comment. Maybe it could be above this code cell?

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +With batch size BS and repeat count RPT, at every step n = (BS * RPT) examples
rename `BS` to `BATCH_SIZE` and `RPT` to `REPEAT_COUNT` also in markdown

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +In order to evaluate at least N total examples, do ceil(N / n) steps
How about

In order to evaluate at least N total examples, apply the ceiling function:  `ceil(N / n)` to calculate necessary steps - here using `//` Python operator

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +        activations = layers.Flatten()(images)
could it look better with new lines between all those `with` blocks?

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +    r = ipu.loops.repeat(REPEAT_COUNT, model, [learning_rate], infeed_queue)
would be nice to name the parameters here

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +Configure the IPU.
would be nice to link
https://docs.graphcore.ai/projects/tensorflow1-user-guide/en/latest/perf_training.html?highlight=auto_select_ipus#selecting-the-number-of-replicas

To explain what `auto_select_ipus` does

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +            if losses is not None and len(losses):
this is interesting. Could it be because `losses` was not initialized in this context? So its `None` only in the first loop iteration? Might be good to check

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +the optimizer.
you could add one more sentence that each device will receive 4 layers

2021-10-08 08:49 UTC, Adamage commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +The first layer must take the explicit 'learning_rate' (learning rate) argument
'learning_rate'  and the rest of params, could be code styled - `learning_rate`

2021-10-08 10:45 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +for this reason, sharding is not recommended for production models where
It seems to me that the visualizations from PopVision and their comments accurately illustrate what good utilization means

2021-10-08 10:47 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +Note:
But below that is a bulleted list, I'm not sure if that would look better?

2021-10-08 10:50 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +Performing gradient accumulation is valid because summing the gradients across
done

2021-10-08 11:07 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +        activations = layers.Flatten()(images)
Definitely, I add some new lines

2021-10-08 11:09 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +    r = ipu.loops.repeat(REPEAT_COUNT, model, [learning_rate], infeed_queue)
It is :P 
```
LEARNING_RATE = 0.01
[...]
            sess.run(compiled_model, {learning_rate: LEARNING_RATE})
```

2021-10-08 11:18 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +the optimizer.
I am not sure, if there are 4 layers:
```
[...]
        with tf.variable_scope("dense32"):
            activations = layers.Dense(32, activation=tf.nn.relu)(activations)
        with tf.variable_scope("logits"):
            logits = layers.Dense(10)(activations)
        with tf.variable_scope("softmax_ce"):
            cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(
                labels=labels, logits=logits)
        with tf.variable_scope("mean"):
            loss = tf.reduce_mean(cross_entropy)
        with tf.variable_scope("optimizer"):
            optimizer = tf.train.GradientDescentOptimizer(
[...]
```

2021-10-08 11:18 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +the optimizer.
How do we count mean and optimizer :P

2021-10-08 11:23 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +The first layer must take the explicit 'learning_rate' (learning rate) argument
Right, I changed it where I thoung it is desired

2021-10-08 11:49 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/pipelining.py
> +Configure the IPU.
done

2021-10-15 15:18 UTC, dirkbrink requested changes
Reviewed up to the end of step 2...will continue with step 3 onwards next week

2021-10-15 15:18 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +We are ready to compile model again and start the training process.
Now we are ready to compile the model again and start the training process.

2021-10-15 15:18 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
>  $ python3 step2_sharding.py
Remove the command line from all of these outputs from each part of the tutorial. It's technically not part of the output and maybe confuses when you're running the jupyter notebook

2021-10-15 15:18 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Complete working example also can be found in `answers/step2_sharding.py`,
A complete...

2021-10-15 15:18 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Complete working example also can be found in `answers/step2_sharding.py`,
. You can run the working example with the following shell command:

2021-10-18 10:42 UTC, dirkbrink requested changes
Review from part 3 onwards

2021-10-18 10:42 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +    pipeline_op = ipu.pipelining_ops.pipeline(
Could you add the variable scope back in please...it makes it easier to visualise in the graph analyser

2021-10-18 10:42 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Moreover, we will update step calculation. The pipeline API encapsulates the
Next we will update the step calculation.

2021-10-18 10:42 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +The code changes for this step can be found
This line is now redundant given the section you added above

2021-10-18 10:42 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +running the appropriate cell, but an error-free approach would be to use the
but a simpler approach would be

2021-10-18 10:42 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Complete, updated `pipelined_model` looks like that:
looks like this:

2021-10-18 10:42 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Note, stage count has to be power of 2.
Why does it have to be a power of 2?

2021-10-20 09:20 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Note, stage count has to be power of 2.
So yes it's true that the number of IPUs selected has to be a power of 2, but it's possible to map multiple pipeline stages to the same IPU, so the above comment is not true.

2021-10-20 10:21 UTC, dirkbrink requested changes
For each of the 4 steps could you add another print statement before the train() call with something like the below please:

"Starting training for Stage 2 - Sharding"
"Starting training for Stage 1 - Single IPU"
etc

2021-10-20 10:21 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +the cell at top of this notebook. But the 'stages' are currently hardcoded by
...or from the hyperparameter code cell at the top of this file.

2021-10-20 10:21 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +This should take multiple string arguments where each argument defines the
This array should take multiple strings, where each string defines the split point.

2021-10-20 10:21 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +implication is that for N `--split` arguments the model will run on N+1 stages
The implication is that for N `SPLIT` values, the model...

2021-10-20 10:21 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +and IPUs. Let's assume that will create a model_layers dictionary from which we
...and IPUs (if each stage is mapped to a unique IPU).

2021-10-20 10:21 UTC, dirkbrink commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +Note, stage count has to be power of 2.
So maybe the text should be:

Note, stage count has to be a power of 2 if mapping each stage to a unique IPU (since we can only acquire IPUs in powers of 2).

2021-10-21 13:21 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +the cell at top of this notebook. But the 'stages' are currently hardcoded by
done

2021-10-21 13:21 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +This should take multiple string arguments where each argument defines the
done

2021-10-21 13:21 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +implication is that for N `--split` arguments the model will run on N+1 stages
done

2021-10-21 13:21 UTC, plutasnyy commented on feature_examples/tensorflow/pipelining_tf1/pipelining/README.md
> +and IPUs. Let's assume that will create a model_layers dictionary from which we
done

2021-10-22 08:54 UTC, dirkbrink approved these changes
LGTM

2021-10-22 10:39 UTC, merged